name: Deploy to GoDaddy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH and Deploy to GoDaddy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ERP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 118.139.179.71 >> ~/.ssh/known_hosts

          # Deploy only changed files, excluding .git and storage folder
          rsync -avz --delete --exclude=".git" --exclude="storage" -e "ssh -o StrictHostKeyChecking=no" ./ oglo4hn6srn7@118.139.179.71:/home/oglo4hn6srn7/public_html/erp/

      - name: Run Deployment Commands on Server
        run: |
          ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR -tt oglo4hn6srn7@118.139.179.71 << 'EOF'
          export TERM=xterm
          cd /home/oglo4hn6srn7/public_html/erp || exit 1
          /usr/local/bin/ea-php74 artisan config:cache
          /usr/local/bin/ea-php74 artisan route:cache
          /usr/local/bin/ea-php74 artisan view:cache
          exit
          EOF
